"use client";
import { useMemo } from "react";
import { CalendarClock, CheckCircle2, FileText } from "lucide-react";
import { billingRecords, formatINR } from "@/lib/client-finance-data";

export default function BillingInvoiceManagement() {
  const records = useMemo(() => billingRecords, []);
  const spend = records.reduce((sum, record) => sum + record.total, 0);
  const cod = records.reduce((sum, record) => sum + record.cod, 0);
  const codCount = records.filter((record) => record.cod > 0).length;
  return <div className="w-full space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Billing</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Shipment billing and invoices</h1><p className="mt-1 text-sm text-muted-foreground">Billing records will appear when a live finance source is connected.</p></div><div className="grid gap-3 md:grid-cols-2"><Kpi label="Shipment spend" value={records.length ? formatINR(spend) : "Not available"} detail={records.length ? "Base charges, weight adjustments, and tax" : "No billing records available"} icon={<CalendarClock className="size-5" />} /><Kpi label="COD remittance" value={records.length ? formatINR(cod) : "Not available"} detail={records.length ? `${codCount} COD shipments` : "No COD records available"} icon={<CheckCircle2 className="size-5" />} /></div><section className="overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div><h2 className="text-sm font-semibold">Shipment bills</h2><p className="mt-0.5 text-xs text-muted-foreground">Connected billing records will be available here.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-[11px] font-medium text-muted-foreground">{records.length} records</span></div>{records.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-left text-xs"><thead className="bg-muted/40 text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{["Shipment", "Route", "Declared", "Measured", "Billable", "Total", "Status"].map((label) => <th key={label} className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/70">{records.map((record) => <tr key={record.id}><td className="px-4 py-3 font-semibold">{record.id}</td><td className="px-4 py-3">{record.origin} → {record.destination}</td><td className="px-4 py-3">{record.declaredWeight.toFixed(2)} kg</td><td className="px-4 py-3">{record.measuredWeight.toFixed(2)} kg</td><td className="px-4 py-3">{record.billableWeight.toFixed(2)} kg</td><td className="px-4 py-3 font-semibold">{formatINR(record.total)}</td><td className="px-4 py-3">{record.status}</td></tr>)}</tbody></table></div> : <EmptyState />}</section></div>;
}
function Kpi({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <div className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-muted text-primary">{icon}</div></div><p className="mt-5 text-xs text-muted-foreground">{detail}</p></div>; }
function EmptyState() { return <div className="grid min-h-[190px] place-items-center p-6 text-center"><FileText className="size-7 text-muted-foreground/40" /><div><p className="mt-2 text-sm font-medium">No billing records available</p><p className="mt-1 text-xs text-muted-foreground">Invoices and charge details will appear when billing is connected.</p></div></div>; }
