"use client";

import { useState } from "react";
import { Calculator } from "lucide-react";
import { pssApi } from "@/lib/pss-api";

const field = "h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-primary";
type Line = { code: string; label: string; amount: number; marker?: "*" };
type Quote = { lane: string; chargeableWeightKg: number; total: number; lines: Line[] };

export default function PssRateCheck() {
  const [form, setForm] = useState({ account_code: "other", origin_pincode: "", destination_pincode: "", origin_city: "", origin_state: "", destination_city: "", destination_state: "", actual_weight_kg: "", volumetric_weight_kg: "", invoice_value: "" });
  const [quote, setQuote] = useState<Quote | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const calculate = async () => { setLoading(true); setError(""); try { const response = await pssApi<{ data: Quote }>("/v1/pricing/quotes", { method: "POST", body: JSON.stringify({ ...form, actual_weight_kg: Number(form.actual_weight_kg), volumetric_weight_kg: Number(form.volumetric_weight_kg || 0), invoice_value: Number(form.invoice_value || 0) }) }); setQuote(response.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to calculate the PSS rate."); } finally { setLoading(false); } };
  const input = (key: keyof typeof form, label: string, type = "text") => <label className="space-y-1.5"><span className="text-xs font-medium">{label}</span><input className={field} type={type} value={form[key]} onChange={(event) => update(key, event.target.value)} /></label>;
  return <div className="w-full space-y-5"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Pricing</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">PSS B2B rate calculator</h1><p className="mt-1 text-sm text-muted-foreground">Client-facing Delhivery B2B pricing from the assigned PSS rate card.</p></header><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,0.9fr)]"><section className="space-y-4 rounded-xl border border-border bg-card p-4"><div className="flex items-center gap-2"><Calculator className="size-4 text-primary" /><h2 className="text-sm font-semibold">Shipment inputs</h2></div><div className="grid gap-3 sm:grid-cols-2">{input("origin_pincode", "Pickup pincode")}{input("destination_pincode", "Delivery pincode")}{input("origin_city", "Pickup city")}{input("origin_state", "Pickup state")}{input("destination_city", "Delivery city")}{input("destination_state", "Delivery state")}{input("actual_weight_kg", "Actual weight (kg)", "number")}{input("volumetric_weight_kg", "Volumetric weight (kg)", "number")}{input("invoice_value", "Invoice value (₹)", "number")}<label className="space-y-1.5"><span className="text-xs font-medium">Delhivery B2B account</span><select className={field} value={form.account_code} onChange={(event) => update("account_code", event.target.value)}><option value="04">04</option><option value="08">08</option><option value="other">Other account</option></select></label></div>{error && <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-xs text-destructive">{error}</p>}<button type="button" disabled={loading} onClick={() => void calculate()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-xs font-semibold text-primary-foreground disabled:opacity-50">{loading ? "Calculating…" : "Calculate PSS rate"}</button></section><section className="rounded-xl border border-border bg-card p-4" aria-live="polite"><h2 className="text-sm font-semibold">PSS B2B quote</h2>{quote ? <div className="mt-4 space-y-3"><div className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{quote.lane} · {quote.chargeableWeightKg} kg charged</span><strong>₹{quote.total.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</strong></div><div className="space-y-2 border-t border-border pt-3">{quote.lines.map((line) => <div key={line.code} className="flex justify-between text-sm"><span>{line.label}{line.marker ?? ""}</span><span>₹{line.amount.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</span></div>)}</div><p className="border-t border-border pt-3 text-[11px] text-muted-foreground">Only the PSS Logistics client charge is shown. Courier rates and provider responses are never displayed.</p></div> : <div className="grid min-h-[280px] place-items-center text-center text-sm text-muted-foreground">Enter shipment details to calculate your PSS charge.</div>}</section></div></div>;
}
