"use client";

import { useEffect, useState } from "react";
import { Bell, Check, ChevronRight, CreditCard, KeyRound, LockKeyhole, PlugZap, SlidersHorizontal, WalletCards, X } from "lucide-react";
import { cn } from "@/lib/utils";

type Section = "preferences" | "notifications" | "security" | "billing" | "integrations";
type SettingsState = { warehouse: string; courier: string; reportRange: string; notifications: Record<string, boolean>; lowBalance: string; billingEmail: string };
const STORAGE_KEY = "pss-client-settings";
const initialSettings: SettingsState = { warehouse: "Noida Main Warehouse", courier: "Delhivery", reportRange: "Current month", notifications: { shipment: true, operations: true, finance: true, support: true }, lowBalance: "5000", billingEmail: "accounts@psslogistics.in" };
const sections: { id: Section; label: string; description: string; icon: typeof SlidersHorizontal }[] = [
  { id: "preferences", label: "Workspace preferences", description: "Defaults used while operating shipments", icon: SlidersHorizontal },
  { id: "notifications", label: "Notifications", description: "Choose the events that need your attention", icon: Bell },
  { id: "security", label: "Security", description: "Protect this client account", icon: LockKeyhole },
  { id: "billing", label: "Wallet & billing", description: "Control finance alerts and delivery", icon: WalletCards },
  { id: "integrations", label: "Integrations", description: "Connections for future workflows", icon: PlugZap },
];
const input = "h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";
const button = "inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border border-input px-3 text-xs font-semibold transition hover:bg-accent";

export default function Settings() {
  const [active, setActive] = useState<Section>("preferences");
  const [settings, setSettings] = useState(initialSettings);
  const [notice, setNotice] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { try { const stored = window.localStorage.getItem(STORAGE_KEY); if (stored) setSettings({ ...initialSettings, ...JSON.parse(stored) }); } catch { /* Keep deterministic demo defaults. */ } }, 0); return () => window.clearTimeout(timer); }, []);
  const save = (next: SettingsState = settings) => { setSettings(next); window.localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setNotice("Settings saved for this demo account."); };
  const update = <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const toggleNotification = (key: string) => update("notifications", { ...settings.notifications, [key]: !settings.notifications[key] });
  return <div className="w-full">
    {notice && <div role="status" className="flex items-center justify-between rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-3 py-2 text-xs text-emerald-700 dark:text-emerald-300"><span className="flex items-center gap-1.5"><Check className="size-3.5" />{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss confirmation"><X className="size-3.5" /></button></div>}
    <div className="grid items-start gap-4 lg:grid-cols-[230px_minmax(0,1fr)]">
      <nav className="h-fit self-start py-1 lg:pr-5">{sections.map((section) => { const Icon = section.icon; return <button key={section.id} type="button" onClick={() => { setActive(section.id); setNotice(""); }} className={cn("flex min-h-[58px] w-full items-center gap-2.5 px-1 py-2.5 text-left transition", active === section.id ? "text-primary" : "text-muted-foreground hover:text-foreground")}><Icon className="size-4 shrink-0" /><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{section.label}</span><span className="mt-0.5 block truncate text-[10px] opacity-75">{section.description}</span></span><ChevronRight className="size-3.5 shrink-0 opacity-50" /></button>; })}</nav>
      <section className="min-w-0">
        {active === "preferences" && <Preferences settings={settings} update={update} save={save} />}
        {active === "notifications" && <Notifications settings={settings} toggle={toggleNotification} save={save} />}
        {active === "security" && <Security setNotice={setNotice} />}
        {active === "billing" && <Billing settings={settings} update={update} save={save} />}
        {active === "integrations" && <Integrations />}
      </section>
    </div>
  </div>;
}

function SectionHeader({ title, detail, icon: Icon }: { title: string; detail: string; icon: typeof SlidersHorizontal }) { return <div className="border-b border-border/70 px-4 py-4 sm:px-5"><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><h2 className="text-sm font-semibold">{title}</h2></div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
function Choice({ label, value, selected, onClick }: { label: string; value: string; selected: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("border-b-2 px-1 py-2 text-left text-xs transition", selected ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:border-border hover:text-foreground")}><span className="block font-semibold">{label}</span><span className="mt-0.5 block text-[10px] opacity-70">{value}</span></button>; }
function Preferences({ settings, update, save }: { settings: SettingsState; update: <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => void; save: () => void }) { return <><SectionHeader title="Workspace preferences" detail="These defaults keep booking and reporting consistent across your account." icon={SlidersHorizontal} /><div className="space-y-5 p-4 sm:p-5"><SettingGroup label="Default warehouse" detail="Used as the starting pickup location in booking."><div className="grid gap-2 sm:grid-cols-2"><Choice label="Noida Main Warehouse" value="Uttar Pradesh · 201301" selected={settings.warehouse === "Noida Main Warehouse"} onClick={() => update("warehouse", "Noida Main Warehouse")} /><Choice label="Bengaluru Fulfilment Hub" value="Karnataka · 560100" selected={settings.warehouse === "Bengaluru Fulfilment Hub"} onClick={() => update("warehouse", "Bengaluru Fulfilment Hub")} /></div></SettingGroup><SettingGroup label="Preferred courier" detail="Your preferred option remains changeable for each shipment."><div className="flex flex-wrap gap-2">{["Delhivery", "Blue Dart", "DTDC"].map((courier) => <Choice key={courier} label={courier} value="Preferred service" selected={settings.courier === courier} onClick={() => update("courier", courier)} />)}</div></SettingGroup><SettingGroup label="Default report range" detail="Applied when opening Reports; the range can still be changed there."><div className="flex flex-wrap gap-2">{["Current month", "Previous month", "Last 30 days"].map((range) => <Choice key={range} label={range} value="Reports and exports" selected={settings.reportRange === range} onClick={() => update("reportRange", range)} />)}</div></SettingGroup><SaveBar save={save} /></div></>; }
function Notifications({ settings, toggle, save }: { settings: SettingsState; toggle: (key: string) => void; save: () => void }) { const rows = [["shipment", "Shipment milestones", "Booking, pickup, in-transit, and delivery updates."], ["operations", "Operations attention", "NDR, exceptions, failed pickups, and RTO events."], ["finance", "Wallet and billing", "Low balance, invoices, weight disputes, and COD remittance."], ["support", "Support activity", "Ticket replies, escalations, and resolution updates."]]; return <><SectionHeader title="Notifications" detail="Keep important logistics events visible without filling the workspace with noise." icon={Bell} /><div className="divide-y divide-border/70 p-4 sm:p-5">{rows.map(([key, label, detail]) => <button key={key} type="button" onClick={() => toggle(key)} className="flex w-full items-center gap-3 py-3 text-left first:pt-0 last:pb-0"><span className={cn("grid size-5 place-items-center rounded-md border transition", settings.notifications[key] ? "border-primary bg-primary text-primary-foreground" : "border-input")}><Check className={cn("size-3", !settings.notifications[key] && "opacity-0")} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{label}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{detail}</span></span><span className="text-[10px] font-semibold text-muted-foreground">{settings.notifications[key] ? "On" : "Off"}</span></button>)}<SaveBar save={save} /></div></>; }
function Security({ setNotice }: { setNotice: (value: string) => void }) { return <><SectionHeader title="Security" detail="Account protection controls for the current client user." icon={LockKeyhole} /><div className="space-y-3 p-4 sm:p-5"><ActionRow icon={KeyRound} title="Password" detail="Last changed 90 days ago" action="Change password" onClick={() => setNotice("Password management will be connected later.")} /><ActionRow icon={LockKeyhole} title="Two-factor authentication" detail="Add an extra verification step at sign-in" action="Set up later" onClick={() => setNotice("Two-factor authentication will be connected later.")} /><ActionRow icon={CreditCard} title="Active sessions" detail="Review where this account is currently signed in" action="View later" onClick={() => setNotice("Session management will be connected later.")} /></div></>; }
function Billing({ settings, update, save }: { settings: SettingsState; update: <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => void; save: () => void }) { return <><SectionHeader title="Wallet & billing preferences" detail="Choose how finance-related account events reach you." icon={WalletCards} /><div className="space-y-5 p-4 sm:p-5"><SettingGroup label="Low balance alert" detail="Show a notification when the wallet falls below this amount."><div className="max-w-xs"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">₹</span><input className={cn(input, "pl-8")} inputMode="numeric" value={settings.lowBalance} onChange={(event) => update("lowBalance", event.target.value)} /></div></div></SettingGroup><SettingGroup label="Billing email" detail="Used for invoice and COD remittance notifications."><input className={input} type="email" value={settings.billingEmail} onChange={(event) => update("billingEmail", event.target.value)} /></SettingGroup><SaveBar save={save} /></div></>; }
function Integrations() { return <><SectionHeader title="Integrations" detail="These connections will bring shipment data into your operating workflow." icon={PlugZap} /><div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-5"><Placeholder title="API keys & webhooks" detail="Connect your own systems to bookings, tracking, billing, and status events." /><Placeholder title="Sales channels" detail="Connect Shopify, WooCommerce, marketplaces, or custom order sources." /><Placeholder title="Courier connections" detail="Courier connectivity and credentials will be managed by PSS." /><Placeholder title="Communication channels" detail="Email, SMS, and WhatsApp delivery controls will be available later." /></div></>; }
function SettingGroup({ label, detail, children }: { label: string; detail: string; children: React.ReactNode }) { return <div className="border-b border-border/50 pb-5 last:border-b-0"><p className="text-xs font-semibold">{label}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p><div className="mt-3">{children}</div></div>; }
function SaveBar({ save }: { save: () => void }) { return <div className="flex justify-end border-t border-border/70 pt-4"><button type="button" onClick={save} className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-primary/90"><Check className="size-3.5" />Save changes</button></div>; }
function ActionRow({ icon: Icon, title, detail, action, onClick }: { icon: typeof KeyRound; title: string; detail: string; action: string; onClick: () => void }) { return <div className="flex items-center gap-3 border-b border-border/50 py-4 first:pt-0 last:border-b-0 last:pb-0"><Icon className="size-4 shrink-0 text-primary" /><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{title}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{detail}</p></div><button type="button" onClick={onClick} className={button}>{action}</button></div>; }
function Placeholder({ title, detail }: { title: string; detail: string }) { return <div className="border-b border-border/50 py-4 first:pt-0 last:border-b-0"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{title}</p><span className="text-[9px] font-semibold uppercase tracking-wide text-muted-foreground">Will do later</span></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{detail}</p></div>; }
