"use client";

import { useEffect, useState } from "react";
import { Bell, Check, ChevronRight, CreditCard, KeyRound, LockKeyhole, PlugZap, SlidersHorizontal, WalletCards, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { pssApi } from "@/lib/pss-api";
import { createClient } from "@/lib/supabase/client";

type Section = "preferences" | "notifications" | "security" | "billing" | "integrations";
type SettingsState = { warehouse: string; courier: string; reportRange: string; notifications: Record<string, boolean>; lowBalance: string; billingEmail: string };
type WarehouseOption = { id: string; name: string; city?: string; pincode?: string };
type ProviderState = { configured?: boolean; enabled?: boolean; health?: string; last_error_code?: string | null; capabilities?: string[]; activation_blockers?: string[] };
const initialSettings: SettingsState = { warehouse: "", courier: "", reportRange: "Current month", notifications: { shipment: false, operations: false, finance: false, support: false }, lowBalance: "", billingEmail: "" };
const sections: { id: Section; label: string; description: string; icon: typeof SlidersHorizontal }[] = [
  { id: "preferences", label: "Workspace preferences", description: "Defaults used while operating shipments", icon: SlidersHorizontal },
  { id: "notifications", label: "Notifications", description: "Choose the events that need your attention", icon: Bell },
  { id: "security", label: "Security", description: "Protect this client account", icon: LockKeyhole },
  { id: "billing", label: "Wallet & billing", description: "Control finance alerts and delivery", icon: WalletCards },
  { id: "integrations", label: "Integrations", description: "Connections for future workflows", icon: PlugZap },
];
const input = "h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";
const button = "inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border border-input px-3 text-xs font-semibold transition hover:bg-accent";

export default function Settings() {
  const [active, setActive] = useState<Section>("preferences");
  const [settings, setSettings] = useState(initialSettings);
  const [warehouses, setWarehouses] = useState<WarehouseOption[]>([]);
  const [couriers, setCouriers] = useState<string[]>([]);
  const [notice, setNotice] = useState("");
  useEffect(() => { void Promise.all([pssApi<{ data: { preferences?: Partial<SettingsState> } }>("/v1/preferences"), pssApi<{ data: Array<Record<string, unknown>> }>("/v1/warehouses"), pssApi<{ data: Record<string, { enabled?: boolean }> }>("/v1/provider-capabilities")]).then(([preferences, warehouseResult, providers]) => { setSettings((current) => ({ ...current, ...(preferences.data.preferences ?? {}) })); setWarehouses(warehouseResult.data.map((row) => ({ id: String(row.id), name: String(row.name ?? "Unnamed warehouse"), city: row.city ? String(row.city) : undefined, pincode: row.pincode ? String(row.pincode) : undefined }))); setCouriers(Object.entries(providers.data).filter(([, value]) => value.enabled === true).map(([provider]) => provider)); }).catch((error) => setNotice(error instanceof Error ? error.message : "Unable to load production preferences.")); }, []);
  const save = async (next: SettingsState = settings) => { setSettings(next); try { await pssApi("/v1/preferences", { method: "PUT", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ preferences: next }) }); setNotice("Settings saved to production."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save production preferences."); } };
  const update = <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const toggleNotification = (key: string) => update("notifications", { ...settings.notifications, [key]: !settings.notifications[key] });
  return <div className="w-full">
    {notice && <div role="status" className="flex items-center justify-between rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-3 py-2 text-xs text-emerald-700 dark:text-emerald-300"><span className="flex items-center gap-1.5"><Check className="size-3.5" />{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss confirmation"><X className="size-3.5" /></button></div>}
    <div className="grid items-start gap-4 lg:grid-cols-[230px_minmax(0,1fr)]">
      <nav className="h-fit self-start py-1 lg:pr-5">{sections.map((section) => { const Icon = section.icon; return <button key={section.id} type="button" onClick={() => { setActive(section.id); setNotice(""); }} className={cn("flex min-h-[58px] w-full items-center gap-2.5 px-1 py-2.5 text-left transition", active === section.id ? "text-primary" : "text-muted-foreground hover:text-foreground")}><Icon className="size-4 shrink-0" /><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{section.label}</span><span className="mt-0.5 block truncate text-[10px] opacity-75">{section.description}</span></span><ChevronRight className="size-3.5 shrink-0 opacity-50" /></button>; })}</nav>
      <section className="min-w-0">
        {active === "preferences" && <Preferences settings={settings} update={update} save={save} warehouses={warehouses} couriers={couriers} />}
        {active === "notifications" && <Notifications settings={settings} toggle={toggleNotification} save={save} />}
        {active === "security" && <Security setNotice={setNotice} />}
        {active === "billing" && <Billing settings={settings} update={update} save={save} />}
        {active === "integrations" && <Integrations />}
      </section>
    </div>
  </div>;
}

function SectionHeader({ title, detail, icon: Icon }: { title: string; detail: string; icon: typeof SlidersHorizontal }) { return <div className="border-b border-border/70 px-4 py-4 sm:px-5"><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><h2 className="text-sm font-semibold">{title}</h2></div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
function Choice({ label, value, selected, onClick }: { label: string; value: string; selected: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("border-b-2 px-1 py-2 text-left text-xs transition", selected ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:border-border hover:text-foreground")}><span className="block font-semibold">{label}</span><span className="mt-0.5 block text-[10px] opacity-70">{value}</span></button>; }
function Preferences({ settings, update, save, warehouses, couriers }: { settings: SettingsState; update: <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => void; save: () => void; warehouses: WarehouseOption[]; couriers: string[] }) { return <><SectionHeader title="Workspace preferences" detail="These defaults keep booking and reporting consistent across your account." icon={SlidersHorizontal} /><div className="space-y-5 p-4 sm:p-5"><SettingGroup label="Default warehouse" detail="Used as the starting pickup location in booking."><div className="grid gap-2 sm:grid-cols-2">{warehouses.map((warehouse) => <Choice key={warehouse.id} label={warehouse.name} value={[warehouse.city, warehouse.pincode].filter(Boolean).join(" · ") || "Production warehouse"} selected={settings.warehouse === warehouse.id} onClick={() => update("warehouse", warehouse.id)} />)}{!warehouses.length && <p className="rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground">No production warehouses are available yet.</p>}</div></SettingGroup><SettingGroup label="Preferred courier" detail="Only courier providers enabled by the production API are selectable."><div className="flex flex-wrap gap-2">{couriers.map((courier) => <Choice key={courier} label={courier[0].toUpperCase() + courier.slice(1)} value="Enabled production provider" selected={settings.courier === courier} onClick={() => update("courier", courier)} />)}{!couriers.length && <p className="rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground">No courier provider is enabled for this account.</p>}</div></SettingGroup><SettingGroup label="Default report range" detail="Applied when opening Reports; the range can still be changed there."><div className="flex flex-wrap gap-2">{["Current month", "Previous month", "Last 30 days"].map((range) => <Choice key={range} label={range} value="Reports and exports" selected={settings.reportRange === range} onClick={() => update("reportRange", range)} />)}</div></SettingGroup><SaveBar save={save} /></div></>; }
function Notifications({ settings, toggle, save }: { settings: SettingsState; toggle: (key: string) => void; save: () => void }) { const rows = [["shipment", "Shipment milestones", "Booking, pickup, in-transit, and delivery updates."], ["operations", "Operations attention", "NDR, exceptions, failed pickups, and RTO events."], ["finance", "Wallet and billing", "Low balance, invoices, weight disputes, and COD remittance."], ["support", "Support activity", "Ticket replies, escalations, and resolution updates."]]; return <><SectionHeader title="Notifications" detail="Keep important logistics events visible without filling the workspace with noise." icon={Bell} /><div className="divide-y divide-border/70 p-4 sm:p-5">{rows.map(([key, label, detail]) => <button key={key} type="button" onClick={() => toggle(key)} className="flex w-full items-center gap-3 py-3 text-left first:pt-0 last:pb-0"><span className={cn("grid size-5 place-items-center rounded-md border transition", settings.notifications[key] ? "border-primary bg-primary text-primary-foreground" : "border-input")}><Check className={cn("size-3", !settings.notifications[key] && "opacity-0")} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{label}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{detail}</span></span><span className="text-[10px] font-semibold text-muted-foreground">{settings.notifications[key] ? "On" : "Off"}</span></button>)}<SaveBar save={save} /></div></>; }
function Security({ setNotice }: { setNotice: (value: string) => void }) { const [open, setOpen] = useState(false); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [saving, setSaving] = useState(false); const changePassword = async () => { if (password.length < 8 || password !== confirm) { setNotice("Use a matching password of at least 8 characters."); return; } setSaving(true); try { const supabase = createClient(); const result = await supabase.auth.updateUser({ password }); if (result.error) throw result.error; const completion = await supabase.rpc("complete_password_change"); if (completion.error) throw completion.error; setPassword(""); setConfirm(""); setOpen(false); setNotice("Password changed successfully."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to change password."); } finally { setSaving(false); } }; return <><SectionHeader title="Security" detail="Account protection controls for the current client user." icon={LockKeyhole} /><div className="space-y-3 p-4 sm:p-5"><ActionRow icon={KeyRound} title="Password" detail="Change the password for this signed-in account" action="Change password" onClick={() => setOpen(true)} /><ActionRow icon={LockKeyhole} title="Two-factor authentication" detail="This account does not have MFA enabled yet" action="Unavailable" onClick={() => setNotice("MFA is not enabled for this account.")} /><ActionRow icon={CreditCard} title="Active sessions" detail="Session revocation is managed by Supabase Auth administration" action="Contact admin" onClick={() => setNotice("Ask a PSS administrator to revoke active sessions.")} /></div>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-background/70 p-4" onClick={() => setOpen(false)}><div className="w-full max-w-md space-y-4 rounded-xl border border-border bg-card p-5 shadow-xl" onClick={(event) => event.stopPropagation()}><h2 className="text-base font-semibold">Change password</h2><input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="New password (at least 8 characters)" className={input} /><input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="Confirm new password" className={input} /><div className="flex justify-end gap-2"><button type="button" className={button} onClick={() => setOpen(false)}>Cancel</button><button type="button" disabled={saving} className="h-9 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground disabled:opacity-50" onClick={() => void changePassword()}>{saving ? "Saving…" : "Change password"}</button></div></div></div>}</>; }
function Billing({ settings, update, save }: { settings: SettingsState; update: <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => void; save: () => void }) { return <><SectionHeader title="Wallet & billing preferences" detail="Choose how finance-related account events reach you." icon={WalletCards} /><div className="space-y-5 p-4 sm:p-5"><SettingGroup label="Low balance alert" detail="Show a notification when the wallet falls below this amount."><div className="max-w-xs"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">₹</span><input className={cn(input, "pl-8")} inputMode="numeric" value={settings.lowBalance} onChange={(event) => update("lowBalance", event.target.value)} /></div></div></SettingGroup><SettingGroup label="Billing email" detail="Used for invoice and COD remittance notifications."><input className={input} type="email" value={settings.billingEmail} onChange={(event) => update("billingEmail", event.target.value)} /></SettingGroup><SaveBar save={save} /></div></>; }
function Integrations() {
  const [providers, setProviders] = useState<Record<string, ProviderState>>({});
  const [providerLoadError, setProviderLoadError] = useState("");
  useEffect(() => { void pssApi<{ data: Record<string, ProviderState> }>("/v1/provider-capabilities").then((result) => { setProviders(result.data ?? {}); setProviderLoadError(""); }).catch((error) => { setProviders({}); setProviderLoadError(error instanceof Error ? error.message : "Live provider status could not be loaded."); }); }, []);
  const providerEntries: Array<[string, ProviderState]> = Object.entries(providers).length ? Object.entries(providers).sort(([left], [right]) => left.localeCompare(right)) : ["delhivery", "trackon", "xpressbees", "rivigo"].map((provider) => [provider, { activation_blockers: [providerLoadError ? "live_status_unavailable" : "not_configured_for_this_account"] }]);
  return <><SectionHeader title="Integrations" detail="Production provider status is read from the authenticated Worker boundary." icon={PlugZap} /><div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-5"><div className="rounded-xl border border-border/70 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">Courier providers</p><span className="text-[9px] font-semibold uppercase tracking-wide text-muted-foreground">Server controlled</span></div>{providerLoadError && <p role="status" className="mt-3 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-[10px] text-amber-800 dark:text-amber-200">Live provider status is unavailable. No courier can be selected until the Worker responds successfully.</p>}<div className="mt-3 space-y-2">{providerEntries.map(([provider, state]) => { const degraded = state.health === "degraded"; const checking = state.health === "pending"; const label = degraded ? "Degraded" : checking ? "Checking" : state.enabled ? "Enabled" : state.configured ? "Configured, disabled" : "Unavailable"; return <div key={provider} className="rounded-lg bg-muted/40 px-3 py-2 text-xs"><div className="flex items-center justify-between gap-3"><span className="font-medium">{provider[0].toUpperCase() + provider.slice(1)}</span><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold", degraded ? "bg-amber-500/15 text-amber-700 dark:text-amber-300" : checking ? "bg-sky-500/15 text-sky-700 dark:text-sky-300" : state.enabled ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-muted text-muted-foreground")}>{label}</span></div>{degraded && state.last_error_code ? <p className="mt-1 text-[10px] text-amber-700 dark:text-amber-300">Recent provider error: {state.last_error_code}</p> : null}{!state.enabled && !degraded && <p className="mt-1 text-[10px] text-muted-foreground">{state.activation_blockers?.join(" · ") || "Provider activation is not available for this account."}</p>}{state.capabilities?.length ? <p className="mt-1 text-[10px] text-muted-foreground">Capabilities: {state.capabilities.join(" · ")}</p> : null}</div>; })}</div></div><Placeholder title="API keys & webhooks" detail="External credentials are managed server-side by PSS and are never exposed in this panel." /><Placeholder title="Sales channels" detail="No production sales-channel connector is enabled for this account." /><Placeholder title="Communication channels" detail="No production communication connector is enabled for this account." /></div></>;
}
function SettingGroup({ label, detail, children }: { label: string; detail: string; children: React.ReactNode }) { return <div className="border-b border-border/50 pb-5 last:border-b-0"><p className="text-xs font-semibold">{label}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p><div className="mt-3">{children}</div></div>; }
function SaveBar({ save }: { save: () => void }) { return <div className="flex justify-end border-t border-border/70 pt-4"><button type="button" onClick={save} className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-primary/90"><Check className="size-3.5" />Save changes</button></div>; }
function ActionRow({ icon: Icon, title, detail, action, onClick }: { icon: typeof KeyRound; title: string; detail: string; action: string; onClick: () => void }) { return <div className="flex items-center gap-3 border-b border-border/50 py-4 first:pt-0 last:border-b-0 last:pb-0"><Icon className="size-4 shrink-0 text-primary" /><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{title}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{detail}</p></div><button type="button" onClick={onClick} className={button}>{action}</button></div>; }
function Placeholder({ title, detail }: { title: string; detail: string }) { return <div className="border-b border-border/50 py-4 first:pt-0 last:border-b-0"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{title}</p><span className="text-[9px] font-semibold uppercase tracking-wide text-muted-foreground">Unavailable</span></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{detail}</p></div>; }
