"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import {
  Activity, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Clipboard,
  Download, FileSpreadsheet, FileText, Filter, History, Info, MapPin, Package,
  RefreshCw, Search, Truck, X, AlertTriangle, Copy, Printer, LifeBuoy,
} from "lucide-react";
import Dropdown from "@/components/ui/dropdown";

type Status = "Booked" | "Picked up" | "In transit" | "Out for delivery" | "Delivered" | "Delayed" | "Exception" | "Returned" | "Cancelled";
type Event = { title: string; description: string; location: string; date: string; time: string; status: Status };
type Action = { title: string; description: string; actor: string; source: "user" | "system" | "bulk"; date: string; time: string; severity: "info" | "success" | "warning" | "error" };
type Shipment = {
  id: string; client: string; clientCode: string; courierTracking: string; pssTracking: string;
  courier: string; mode: string; service: string; origin: string; originCountry: string;
  destination: string; destinationCountry: string; status: Status; progress: number;
  pieces: number; weight: string; eta: string; booked: string; expected: string;
  payment: string; value: string; updated: string; events: Event[]; actions: Action[]; delay?: string;
};
type Filters = { status: Status | ""; courier: string; mode: string; origin: string; destination: string; delayed: boolean; exceptions: boolean };

const statusList: Status[] = ["Booked", "Picked up", "In transit", "Out for delivery", "Delivered", "Delayed", "Exception", "Returned", "Cancelled"];
const statusProgress: Record<Status, number> = { Booked: 10, "Picked up": 20, "In transit": 55, "Out for delivery": 85, Delivered: 100, Delayed: 55, Exception: 45, Returned: 35, Cancelled: 0 };
const statusStyles: Record<Status, string> = {
  Booked: "bg-blue-500/10 text-blue-700 border-blue-500/20 dark:text-blue-300", "Picked up": "bg-sky-500/10 text-sky-700 border-sky-500/20 dark:text-sky-300",
  "In transit": "bg-sky-500/10 text-sky-700 border-sky-500/20 dark:text-sky-300", "Out for delivery": "bg-amber-500/10 text-amber-700 border-amber-500/20 dark:text-amber-300",
  Delivered: "bg-emerald-500/10 text-emerald-700 border-emerald-500/20 dark:text-emerald-300", Delayed: "bg-amber-500/10 text-amber-700 border-amber-500/20 dark:text-amber-300",
  Exception: "bg-destructive/10 text-destructive border-destructive/20", Returned: "bg-violet-500/10 text-violet-700 border-violet-500/20 dark:text-violet-300", Cancelled: "bg-muted text-muted-foreground border-border",
};
const initialFilters: Filters = { status: "", courier: "", mode: "", origin: "", destination: "", delayed: false, exceptions: false };

const makeEvents = (status: Status, origin: string, destination: string, booked: string): Event[] => {
  const all: Event[] = [
    { title: "Shipment booked", description: "Booking created and documentation verified", location: origin, date: booked, time: "09:20 AM", status: "Booked" },
    { title: "Shipment picked up from origin", description: "Courier accepted the shipment at handover", location: origin, date: "2026-08-02", time: "02:15 PM", status: "Picked up" },
    { title: "Cargo loaded onto vehicle", description: "Shipment departed the origin facility", location: "Bengaluru Hub", date: "2026-08-03", time: "06:40 PM", status: "In transit" },
    { title: "Arrived at destination facility", description: "Shipment reached the destination processing centre", location: destination, date: "2026-08-05", time: "08:10 AM", status: "In transit" },
  ];
  if (status === "Out for delivery") all.push({ title: "Out for delivery", description: "Courier is carrying the shipment for final delivery", location: destination, date: "2026-08-06", time: "08:35 AM", status });
  if (status === "Delivered") all.push({ title: "Delivered", description: "Shipment delivered and recipient confirmation recorded", location: destination, date: "2026-08-06", time: "11:42 AM", status });
  if (status === "Exception") all.push({ title: "Delivery exception reported", description: "Address confirmation is required before the next attempt", location: destination, date: "2026-08-06", time: "10:05 AM", status });
  if (status === "Delayed") all.push({ title: "Delivery delayed", description: "Weather disruption changed the expected delivery window", location: destination, date: "2026-08-06", time: "07:50 AM", status });
  return all.filter((event, index) => index < (status === "Booked" ? 1 : status === "Picked up" ? 2 : status === "In transit" ? 4 : all.length));
};

const makeActions = (status: Status, courier: string, service: string, booked: string, value: string): Action[] => {
  const actions: Action[] = [
    { title: "Courier selected", description: `${courier} · ${service} service`, actor: "John Doe", source: "user", date: booked, time: "09:32 AM", severity: "info" },
    { title: "Documentation verified", description: `Shipment documents checked for ${value} value`, actor: "System", source: "system", date: booked, time: "09:35 AM", severity: "success" },
  ];
  if (status === "Exception") actions.push({ title: "Exception acknowledged", description: "Address confirmation is required before the next attempt", actor: "John Doe", source: "user", date: "2026-08-06", time: "10:08 AM", severity: "warning" });
  if (status === "Delayed") actions.push({ title: "Delay acknowledged", description: "Delivery window updated after an operational disruption", actor: "System", source: "system", date: "2026-08-06", time: "07:58 AM", severity: "warning" });
  if (status === "Picked up" || status === "Out for delivery" || status === "Delivered") actions.push({ title: "Pickup confirmed", description: "Courier handover recorded against the shipment", actor: "System", source: "system", date: "2026-08-02", time: "02:18 PM", severity: "success" });
  return actions;
};

const clientCodes: Record<string, string> = { "Avacada Badara Clint": "ABC", "Northstar Retail Pvt Ltd": "NRT", "Meridian Foods": "MFD", "Kite Labs": "KTL", "Urban Loom": "URL" };
const createShipment = (id: string, client: string, courierTracking: string, courier: string, origin: string, destination: string, status: Status, mode: string, service: string, pieces: number, weight: string, eta: string, booked: string, expected: string, payment: string, value: string, updated: string, delay?: string): Shipment => ({ id, client, clientCode: clientCodes[client] || "PSS", courierTracking, pssTracking: `${clientCodes[client] || "PSS"}${courierTracking}`, courier, mode, service, origin, originCountry: "India", destination, destinationCountry: "Canada", status, progress: statusProgress[status], pieces, weight, eta, booked, expected, payment, value, updated, delay, events: makeEvents(status, origin, destination, booked), actions: makeActions(status, courier, service, booked, value) });

const shipments: Shipment[] = [
  createShipment("shp-17", "Avacada Badara Clint", "123456789", "Maersk Logistics", "Mumbai", "Toronto", "Picked up", "Air", "Economy", 5, "2.26 t", "in 19 days", "2026-07-18", "2026-08-25", "Prepaid", "₹48,500", "4 days ago"),
  createShipment("shp-47", "Northstar Retail Pvt Ltd", "987654321", "Delhivery", "São Paulo", "New York", "Exception", "Road", "Priority", 2, "18 kg", "on hold", "2026-07-28", "2026-08-08", "COD", "₹18,200", "Today", "Address confirmation required"),
  createShipment("shp-08", "Meridian Foods", "456780012", "Blue Dart", "Shanghai", "Hong Kong", "Booked", "Air", "Express", 8, "42 kg", "in 7 days", "2026-08-04", "2026-08-13", "Prepaid", "₹32,800", "Yesterday"),
  createShipment("shp-05", "Kite Labs", "555120005", "DTDC", "Dubai", "Sydney", "Out for delivery", "Air", "Express", 1, "6.4 kg", "today", "2026-07-30", "2026-08-06", "Prepaid", "₹9,800", "2 hours ago"),
  createShipment("shp-31", "Urban Loom", "776540031", "Shiprocket", "Toronto", "Singapore", "Delayed", "Sea", "Economy", 12, "120 kg", "in 4 days", "2026-07-20", "2026-08-10", "Prepaid", "₹76,000", "Today", "+2 days"),
  createShipment("shp-41", "Avacada Badara Clint", "900110041", "FedEx", "Los Angeles", "Hong Kong", "Delayed", "Air", "Priority", 3, "14 kg", "in 5 days", "2026-07-22", "2026-08-11", "COD", "₹21,300", "Yesterday", "+1 day"),
  createShipment("shp-33", "Meridian Foods", "400770033", "DB Schenker", "São Paulo", "Hamburg", "Delivered", "Air", "Economy", 6, "36 kg", "delivered", "2026-07-15", "2026-08-02", "Prepaid", "₹55,100", "Aug 2"),
  createShipment("shp-39", "Kite Labs", "620330039", "Delhivery", "Shanghai", "London", "Returned", "Road", "Economy", 1, "4 kg", "returned", "2026-07-11", "2026-08-01", "Prepaid", "₹6,100", "Aug 1"),
];

const normalize = (value: string) => value.trim().toLowerCase();
const matchesShipment = (shipment: Shipment, query: string) => !query || [shipment.pssTracking, shipment.courierTracking, shipment.client, shipment.clientCode, shipment.id, shipment.origin, shipment.destination, shipment.courier].some((value) => normalize(value).includes(normalize(query)));
const eventRows = (list: Shipment[]) => list.flatMap((shipment) => shipment.events.map((event, index) => ({ shipment, event, index: index + 1 })));
const esc = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

const crc32 = (bytes: Uint8Array) => { let crc = 0xffffffff; for (const byte of bytes) { crc ^= byte; for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0); } return (crc ^ 0xffffffff) >>> 0; };
const zipStore = (files: { name: string; content: string }[]) => {
  const encoder = new TextEncoder(); const parts: Uint8Array[] = []; const central: Uint8Array[] = []; let offset = 0;
  const p16 = (v: DataView, i: number, n: number) => v.setUint16(i, n, true); const p32 = (v: DataView, i: number, n: number) => v.setUint32(i, n, true);
  files.forEach(({ name, content }) => { const nb = encoder.encode(name); const data = encoder.encode(content); const local = new Uint8Array(30 + nb.length + data.length); const v = new DataView(local.buffer); p32(v, 0, 0x04034b50); p16(v, 4, 20); p32(v, 14, crc32(data)); p32(v, 18, data.length); p32(v, 22, data.length); p16(v, 26, nb.length); local.set(nb, 30); local.set(data, 30 + nb.length); parts.push(local); const dir = new Uint8Array(46 + nb.length); const d = new DataView(dir.buffer); p32(d, 0, 0x02014b50); p16(d, 4, 20); p16(d, 6, 20); p32(d, 16, crc32(data)); p32(d, 20, data.length); p32(d, 24, data.length); p16(d, 28, nb.length); p32(d, 42, offset); dir.set(nb, 46); central.push(dir); offset += local.length; });
  const centralSize = central.reduce((sum, item) => sum + item.length, 0); const end = new Uint8Array(22); const ev = new DataView(end.buffer); p32(ev, 0, 0x06054b50); p16(ev, 8, files.length); p16(ev, 10, files.length); p32(ev, 12, centralSize); p32(ev, 16, offset); const result = new Uint8Array(offset + centralSize + 22); let cursor = 0; [...parts, ...central, end].forEach((part) => { result.set(part, cursor); cursor += part.length; }); return result;
};
const downloadBinary = (name: string, bytes: Uint8Array, type: string) => { const url = URL.createObjectURL(new Blob([bytes.buffer as ArrayBuffer], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500); };
const buildWorkbook = (list: Shipment[], filters: Filters, query: string) => {
  const rows = eventRows(list); const sheet = (header: string[], values: string[][]) => { const row = (data: string[], number: number) => `<row r="${number}">${data.map((value, index) => `<c r="${String.fromCharCode(65 + Math.min(index, 25))}${number}" t="inlineStr"><is><t>${esc(value)}</t></is></c>`).join("")}</row>`; return `<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${row(header, 1)}${values.map((data, index) => row(data, index + 2)).join("")}</sheetData></worksheet>`; };
  const summaryHeader = ["Client", "Client identifier", "PSS tracking number", "Courier tracking number", "Reference", "Courier", "Mode", "Service", "Origin", "Destination", "Status", "Progress", "Booked", "Expected delivery", "Pieces", "Weight", "Payment", "Value", "Last updated"];
  const summaryValues = list.map((s) => [s.client, s.clientCode, s.pssTracking, s.courierTracking, s.id, s.courier, s.mode, s.service, s.origin, s.destination, s.status, `${s.progress}%`, s.booked, s.expected, String(s.pieces), s.weight, s.payment, s.value, s.updated]);
  const eventHeader = ["PSS tracking number", "Courier tracking number", "Client", "Event #", "Status", "Title", "Description", "Location", "Date", "Time"];
  const eventValues = rows.map(({ shipment: s, event, index }) => [s.pssTracking, s.courierTracking, s.client, String(index), event.status, event.title, event.description, event.location, event.date, event.time]);
  const detailHeader = ["Export timestamp", "Search", "Status", "Courier", "Mode", "Origin", "Destination", "Delayed only", "Exceptions only", "Shipments", "Events", "Notice"];
  const detailValues = [[new Date().toISOString(), query || "All", filters.status || "All", filters.courier || "All", filters.mode || "All", filters.origin || "All", filters.destination || "All", String(filters.delayed), String(filters.exceptions), String(list.length), String(rows.length), "Frontend demo data"]];
  const files = [
    { name: "[Content_Types].xml", content: `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet3.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>` },
    { name: "_rels/.rels", content: `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>` },
    { name: "xl/workbook.xml", content: `<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Shipment Summary" sheetId="1" r:id="rId1"/><sheet name="Tracking Events" sheetId="2" r:id="rId2"/><sheet name="Export Details" sheetId="3" r:id="rId3"/></sheets></workbook>` },
    { name: "xl/_rels/workbook.xml.rels", content: `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet3.xml"/></Relationships>` },
    { name: "xl/worksheets/sheet1.xml", content: sheet(summaryHeader, summaryValues) }, { name: "xl/worksheets/sheet2.xml", content: sheet(eventHeader, eventValues) }, { name: "xl/worksheets/sheet3.xml", content: sheet(detailHeader, detailValues) },
  ]; return zipStore(files);
};

const Badge = ({ status }: { status: Status }) => <span className={cn("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold", statusStyles[status])}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
const iconForStatus = (status: Status) => status === "Exception" ? AlertTriangle : status === "Delivered" ? CheckCircle2 : status === "Booked" ? Clipboard : Truck;

export default function ShipmentTracking() {
  const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState(shipments[0].id); const [filters, setFilters] = useState<Filters>(initialFilters);
  const [filterOpen, setFilterOpen] = useState(false); const [exportOpen, setExportOpen] = useState(false); const [mobileDetail, setMobileDetail] = useState(false); const [notice, setNotice] = useState(""); const [refreshing, setRefreshing] = useState(false); const [copied, setCopied] = useState(""); const [sortNewest, setSortNewest] = useState(true); const [sortActionsNewest, setSortActionsNewest] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { const id = new URLSearchParams(window.location.search).get("id"); if (id) { const found = shipments.find((s) => [s.id, s.pssTracking, s.courierTracking].includes(id)); if (found) { setSelectedId(found.id); setMobileDetail(true); } else setNotice(`No shipment matched reference ${id}.`); } }, 0); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => shipments.filter((s) => matchesShipment(s, query) && (!filters.status || s.status === filters.status) && (!filters.courier || s.courier === filters.courier) && (!filters.mode || s.mode === filters.mode) && (!filters.origin || s.origin === filters.origin) && (!filters.destination || s.destination === filters.destination) && (!filters.delayed || s.status === "Delayed") && (!filters.exceptions || s.status === "Exception")), [query, filters]);
  const selected = shipments.find((s) => s.id === selectedId) || filtered[0] || shipments[0];
  const activeFilterCount = Object.values(filters).filter(Boolean).length; const eventList = sortNewest ? [...selected.events].reverse() : selected.events; const actionList = sortActionsNewest ? [...selected.actions].reverse() : selected.actions;
  const selectShipment = (id: string) => { setSelectedId(id); setMobileDetail(true); setNotice(""); };
  const copy = async (value: string, label: string) => { try { await navigator.clipboard.writeText(value); } catch { /* clipboard may be unavailable in demo */ } setCopied(label); setTimeout(() => setCopied(""), 1600); };
  const refresh = () => { setRefreshing(true); setNotice("Tracking data refreshed from the demo feed."); setTimeout(() => setRefreshing(false), 700); };
  const exportExcel = (list: Shipment[] = filtered) => { if (!list.length) return; const bytes = buildWorkbook(list, filters, query); const slug = filters.status ? filters.status.replaceAll(" ", "-") : "filtered"; downloadBinary(`PSS-Tracking-${slug}-${new Date().toISOString().slice(0, 10)}.xlsx`, bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); setExportOpen(false); setNotice(`Excel export ready with ${list.length} shipment${list.length === 1 ? "" : "s"}.`); };
  const resetFilters = () => setFilters(initialFilters);
  const input = "h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none transition placeholder:text-muted-foreground/70 focus:border-primary focus:ring-4 focus:ring-primary/10";

  return <div className="w-full space-y-3">
    <div className="relative flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
      <div className="flex flex-1 flex-wrap items-center gap-2"><div className="relative min-w-[240px] flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input aria-label="Search shipments" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search PSS or courier number…" className={cn(input, "w-full pl-9 pr-8")} />{query && <button type="button" aria-label="Clear search" onClick={() => setQuery("")} className="absolute right-2 top-1/2 -translate-y-1/2 rounded p-1 text-muted-foreground hover:bg-accent"><X className="h-3.5 w-3.5" /></button>}</div><button type="button" onClick={() => setFilterOpen((v) => !v)} className={cn("inline-flex h-9 items-center gap-1.5 rounded-lg border px-3 text-xs font-semibold transition hover:bg-accent", activeFilterCount ? "border-primary/30 bg-primary/5 text-primary" : "border-input text-muted-foreground")}><Filter className="h-3.5 w-3.5" /> Filters{activeFilterCount > 0 && <span className="rounded-full bg-primary px-1.5 text-[10px] text-primary-foreground">{activeFilterCount}</span>}</button><span className="hidden rounded-full border border-border bg-muted/50 px-2.5 py-1 text-[11px] font-medium text-muted-foreground sm:inline-flex">Frontend demo data</span><button type="button" onClick={refresh} className="inline-flex h-9 items-center gap-2 rounded-lg border border-input bg-background px-3 text-xs font-semibold transition hover:bg-accent"><RefreshCw className={cn("h-3.5 w-3.5", refreshing && "animate-spin")} /> Refresh</button><button type="button" onClick={() => setExportOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground shadow-sm transition hover:bg-primary/90"><FileSpreadsheet className="h-3.5 w-3.5" /> Export Excel</button></div>
      {filterOpen && <FilterPanel filters={filters} setFilters={setFilters} reset={resetFilters} close={() => setFilterOpen(false)} />}
    </div>
    {notice && <div role="status" className="flex items-center justify-between rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-xs text-primary"><span>{notice}</span><button type="button" aria-label="Dismiss notice" onClick={() => setNotice("")}><X className="h-3.5 w-3.5" /></button></div>}
    <div className="grid min-h-0 grid-cols-1 gap-5 lg:h-[calc(100vh-10rem)] lg:grid-cols-[320px_minmax(0,1fr)]">
      <section className={cn("overflow-hidden rounded-xl border border-border bg-card shadow-xs lg:flex lg:min-h-0 lg:flex-col", mobileDetail && "hidden lg:flex")}>
        <div className="border-b border-border px-4 py-2.5 text-[11px] text-muted-foreground">{filtered.length} of {shipments.length} shipments</div>
        <div className="max-h-[55vh] divide-y divide-border/70 overflow-y-auto lg:min-h-0 lg:max-h-none lg:flex-1">{filtered.length ? filtered.map((shipment) => <button type="button" key={shipment.id} onClick={() => selectShipment(shipment.id)} className={cn("w-full px-4 py-3.5 text-left transition hover:bg-accent/60", selected.id === shipment.id && "bg-primary/5 ring-inset ring-1 ring-primary/10")}><div className="flex items-start justify-between gap-2"><span className="font-mono text-[11px] font-bold text-foreground">{shipment.pssTracking}</span><Badge status={shipment.status} /></div><p className="mt-1 truncate text-xs text-muted-foreground">{shipment.client} · {shipment.origin} <ArrowRight className="mx-0.5 inline h-3 w-3" /> {shipment.destination}</p><p className="mt-1 text-[10px] text-muted-foreground">Courier {shipment.courierTracking} · {shipment.courier}</p></button>) : <div className="p-8 text-center text-sm text-muted-foreground"><Search className="mx-auto mb-2 h-5 w-5 opacity-50" />No shipments match these filters.</div>}</div>
      </section>
      <section className={cn("space-y-5", !mobileDetail && "hidden lg:block", "lg:flex lg:min-h-0 lg:flex-col")}>
        <div className="flex items-center justify-between lg:hidden"><button type="button" onClick={() => setMobileDetail(false)} className="inline-flex items-center gap-1.5 text-xs font-semibold text-primary"><ArrowLeft className="h-3.5 w-3.5" /> All shipments</button></div>
        <div className="rounded-xl border border-border bg-card p-4 shadow-xs sm:p-5"><div className="flex flex-col gap-3 border-b border-border/70 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-mono text-lg font-bold tracking-tight">{selected.pssTracking}</h2><button type="button" aria-label="Copy PSS tracking number" onClick={() => copy(selected.pssTracking, "PSS number copied")} className="rounded-md p-1 text-muted-foreground hover:bg-accent hover:text-foreground"><Copy className="h-3.5 w-3.5" /></button><Badge status={selected.status} /></div><p className="mt-1 text-sm text-muted-foreground">{selected.client} <span className="mx-1">·</span> client code <span className="font-mono font-semibold text-foreground">{selected.clientCode}</span></p><p className="mt-1 text-xs text-muted-foreground">Courier reference: <span className="font-mono text-foreground">{selected.courierTracking}</span><button type="button" aria-label="Copy courier tracking number" onClick={() => copy(selected.courierTracking, "Courier number copied")} className="ml-1.5 inline-flex align-middle text-muted-foreground hover:text-foreground"><Copy className="h-3 w-3" /></button></p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="rounded-full border border-border px-2.5 py-1">{selected.mode}</span><span className="rounded-full border border-border px-2.5 py-1">{selected.service}</span></div></div>
          <div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><LocationCard label="Origin" city={selected.origin} country={selected.originCountry} icon={<Package className="h-3.5 w-3.5" />} /><span className="grid h-8 w-8 place-items-center rounded-full bg-primary/10 text-primary"><ArrowRight className="h-4 w-4" /></span><LocationCard label="Destination" city={selected.destination} country={selected.destinationCountry} icon={<MapPin className="h-3.5 w-3.5" />} /></div>
          <div className="mt-5"><div className="mb-2 flex items-center justify-between text-xs font-medium"><span>Shipment progress</span><span className="text-primary">{selected.progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all duration-500" style={{ width: `${selected.progress}%` }} /></div>{selected.delay ? <p className="mt-2 flex items-center gap-1.5 text-xs text-amber-700 dark:text-amber-300"><AlertTriangle className="h-3.5 w-3.5" /> {selected.delay}</p> : <p className="mt-2 text-xs text-muted-foreground">Expected delivery <span className="font-semibold text-foreground">{selected.expected}</span> · updated {selected.updated}</p>}</div>
          <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Pieces" value={String(selected.pieces)} /><Metric label="Weight" value={selected.weight} /><Metric label="ETA" value={selected.eta} /><Metric label="Courier" value={selected.courier} /></div>
        </div>
        <div className="grid min-h-0 flex-1 grid-cols-1 gap-5 lg:grid-cols-2">
          <TimelineCard title="Tracking history" subtitle={`${selected.events.length} event${selected.events.length === 1 ? "" : "s"} recorded · last updated ${selected.updated}`} icon={<History className="h-4 w-4 text-primary" />} controlLabel={sortNewest ? "Newest first" : "Journey order"} onToggle={() => setSortNewest((v) => !v)} items={eventList} renderItem={(event, index) => { const Icon = iconForStatus(event.status); return <TimelineItem key={`${event.date}-${event.time}`} icon={<Icon className="h-3.5 w-3.5" />} tone={event.status === "Exception" || event.status === "Delayed" ? "warning" : event.status === "Delivered" ? "success" : "primary"} last={index === eventList.length - 1}><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between"><p className="text-sm font-medium">{event.title}</p><span className="shrink-0 text-[11px] text-muted-foreground">{event.date} · {event.time}</span></div><p className="mt-1 text-xs text-muted-foreground">{event.description}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-muted-foreground"><MapPin className="h-3 w-3" />{event.location}</p></TimelineItem>; }} />
          <TimelineCard title="Actions taken" subtitle={`${selected.actions.length} action${selected.actions.length === 1 ? "" : "s"} recorded`} icon={<ActivityIcon />} controlLabel={sortActionsNewest ? "Newest first" : "Oldest first"} onToggle={() => setSortActionsNewest((v) => !v)} items={actionList} empty="No operator or system actions recorded for this shipment." renderItem={(item, index) => <TimelineItem key={`${item.date}-${item.time}-${item.title}`} icon={<ActionIcon severity={item.severity} />} tone={item.severity} last={index === actionList.length - 1}><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between"><p className="text-sm font-medium">{item.title}</p><span className="shrink-0 text-[11px] text-muted-foreground">{item.date} · {item.time}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.description}</p><p className="mt-1 text-[11px] text-muted-foreground">By <span className="font-medium text-foreground">{item.actor}</span> · <span className="capitalize">{item.source}</span></p></TimelineItem>} />
        </div>
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-xs lg:mt-auto"><div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><span>{selected.payment}</span><span>·</span><span>{selected.value}</span><span>·</span><span>Booked {selected.booked}</span></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-1.5 rounded-lg border border-input px-2.5 py-1.5 text-xs font-semibold hover:bg-accent"><Printer className="h-3.5 w-3.5" /> Print</button><button type="button" onClick={() => setNotice("Support link ready for this demo shipment.")} className="inline-flex items-center gap-1.5 rounded-lg border border-input px-2.5 py-1.5 text-xs font-semibold hover:bg-accent"><LifeBuoy className="h-3.5 w-3.5" /> Support</button><button type="button" onClick={() => exportExcel([selected])} className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-2.5 py-1.5 text-xs font-semibold text-primary-foreground hover:bg-primary/90"><Download className="h-3.5 w-3.5" /> Export shipment</button></div></div>
      </section>
    </div>
    {copied && <div role="status" className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-xs font-semibold text-emerald-700 shadow-lg dark:text-emerald-300"><Check className="mr-1 inline h-3.5 w-3.5" />{copied}</div>}
    {exportOpen && <ExportPanel list={filtered} query={query} close={() => setExportOpen(false)} exportExcel={exportExcel} />}
  </div>;
}

function LocationCard({ label, city, country, icon }: { label: string; city: string; country: string; icon: React.ReactNode }) { return <div className="min-w-0 rounded-lg border border-border bg-background p-3"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{icon}{label}</p><p className="mt-1 truncate text-sm font-semibold">{city}</p><p className="text-xs text-muted-foreground">{country}</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-lg border border-border bg-background p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 truncate text-sm font-semibold" title={value}>{value}</p></div>; }
type TimelineTone = "primary" | "success" | "warning" | "error" | "info";
function TimelineItem({ icon, tone, last, children }: { icon: React.ReactNode; tone: TimelineTone; last: boolean; children: React.ReactNode }) { const toneClass = { primary: "bg-primary/10 text-primary", success: "bg-emerald-500/10 text-emerald-600", warning: "bg-amber-500/10 text-amber-600", error: "bg-destructive/10 text-destructive", info: "bg-violet-500/10 text-violet-600" }[tone]; return <li className="relative flex gap-3 pb-5 last:pb-0"><div className="relative flex w-7 shrink-0 justify-center"><span className={cn("z-10 grid h-7 w-7 place-items-center rounded-full", toneClass)}>{icon}</span>{!last && <span className="absolute top-7 h-full w-px bg-border" />}</div><div className="min-w-0 flex-1">{children}</div></li>; }
function TimelineCard<T>({ title, subtitle, icon, controlLabel, onToggle, items, renderItem, empty }: { title: string; subtitle: string; icon: React.ReactNode; controlLabel: string; onToggle: () => void; items: T[]; renderItem: (item: T, index: number) => React.ReactNode; empty?: string }) { return <div className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="flex flex-col gap-2 border-b border-border/70 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h3 className="flex items-center gap-2 text-sm font-semibold">{icon}{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p></div><button type="button" onClick={onToggle} className="inline-flex items-center gap-1.5 self-start rounded-lg border border-input px-2.5 py-1.5 text-xs font-medium text-muted-foreground hover:bg-accent">{controlLabel}<ChevronDown className="h-3.5 w-3.5" /></button></div>{items.length ? <ol className="min-h-0 flex-1 space-y-0 overflow-y-auto px-4 py-4 sm:px-5">{items.map(renderItem)}</ol> : <div className="flex min-h-40 flex-1 items-center justify-center px-5 text-center text-xs text-muted-foreground">{empty || "No records available."}</div>}</div>; }
function ActivityIcon() { return <Activity className="h-4 w-4 text-violet-500" />; }
function ActionIcon({ severity }: { severity: Action["severity"] }) { if (severity === "warning" || severity === "error") return <AlertTriangle className="h-3.5 w-3.5" />; if (severity === "success") return <CheckCircle2 className="h-3.5 w-3.5" />; return <FileText className="h-3.5 w-3.5" />; }

function FilterPanel({ filters, setFilters, reset, close }: { filters: Filters; setFilters: React.Dispatch<React.SetStateAction<Filters>>; reset: () => void; close: () => void }) {
  const [openKey, setOpenKey] = useState<string | null>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const update = (key: keyof Filters, value: string | boolean) => setFilters((current) => ({ ...current, [key]: value }));
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setOpenKey(null); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => { const onPointerDown = (event: PointerEvent) => { if (panelRef.current && !panelRef.current.contains(event.target as Node)) close(); }; document.addEventListener("pointerdown", onPointerDown); return () => document.removeEventListener("pointerdown", onPointerDown); }, [close]);
  const options = (key: keyof Filters, label: string, values: string[]) => <AppleSelect label={label} value={String(filters[key])} options={["", ...values]} open={openKey === key} onOpen={() => setOpenKey(openKey === key ? null : key)} onChange={(value) => { update(key, value); setOpenKey(null); }} />;
  return <div ref={panelRef} className="absolute right-0 top-full z-50 mt-2 w-[min(100%,28rem)] space-y-3 rounded-xl border border-border bg-popover p-3 text-popover-foreground shadow-lg"><div className="flex items-center justify-between"><p className="text-xs font-semibold">Filter shipments</p><button type="button" onClick={close} aria-label="Close filters"><X className="h-3.5 w-3.5 text-muted-foreground" /></button></div><div className="grid gap-2 sm:grid-cols-2">{options("status", "All statuses", statusList)}{options("courier", "All couriers", [...new Set(shipments.map((s) => s.courier))])}{options("mode", "All modes", [...new Set(shipments.map((s) => s.mode))])}{options("origin", "All origins", [...new Set(shipments.map((s) => s.origin))])}{options("destination", "All destinations", [...new Set(shipments.map((s) => s.destination))])}</div><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={filters.delayed} onChange={(e) => update("delayed", e.target.checked)} className="accent-primary" /> Delayed only</label><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={filters.exceptions} onChange={(e) => update("exceptions", e.target.checked)} className="accent-primary" /> Exceptions only</label><div className="flex justify-between pt-2"><button type="button" onClick={reset} className="text-xs font-semibold text-muted-foreground hover:text-foreground">Clear all</button><button type="button" onClick={close} className="rounded-lg bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground">Apply filters</button></div></div>;
}

function AppleSelect({ label, value, options, open, onOpen, onChange }: { label: string; value: string; options: string[]; open: boolean; onOpen: () => void; onChange: (value: string) => void }) { return <Dropdown label={label} value={value} options={options} open={open} onOpenChange={onOpen} onChange={onChange} />; }

function ExportPanel({ list, query, close, exportExcel }: { list: Shipment[]; query: string; close: () => void; exportExcel: (list?: Shipment[]) => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4 backdrop-blur-sm" onClick={close}><div role="dialog" aria-modal="true" aria-labelledby="export-title" className="w-full max-w-md rounded-2xl border border-border bg-popover p-5 text-popover-foreground shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><FileSpreadsheet className="h-4 w-4 text-primary" /><h2 id="export-title" className="text-base font-semibold">Export tracking data</h2></div><p className="mt-1 text-xs text-muted-foreground">Download a filtered Excel workbook with shipment and event sheets.</p></div><button type="button" onClick={close} aria-label="Close export dialog" className="rounded-lg p-1.5 text-muted-foreground hover:bg-accent"><X className="h-4 w-4" /></button></div><div className="mt-5 space-y-3 rounded-xl border border-border bg-muted/30 p-3 text-xs"><div className="flex items-center justify-between"><span className="text-muted-foreground">Export scope</span><span className="font-semibold">Current search and filters</span></div><div className="flex items-center justify-between"><span className="text-muted-foreground">Search</span><span className="max-w-[210px] truncate font-medium">{query || "All shipments"}</span></div><div className="flex items-center justify-between"><span className="text-muted-foreground">Matching shipments</span><span className="font-semibold text-primary">{list.length}</span></div><div className="flex items-center justify-between"><span className="text-muted-foreground">Tracking events</span><span className="font-semibold text-primary">{eventRows(list).length}</span></div></div><div className="mt-4 flex items-start gap-2 rounded-lg bg-primary/5 p-3 text-xs text-muted-foreground"><Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" /><span>Workbook includes Shipment Summary, Tracking Events, and Export Details. Values are frontend demo data.</span></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border border-input px-3 py-2 text-xs font-semibold hover:bg-accent">Cancel</button><button type="button" disabled={!list.length} onClick={() => exportExcel(list)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50"><Download className="h-3.5 w-3.5" /> Download .xlsx</button></div></div></div>;
}
