"use client";
import { useEffect, useState } from "react";
import { RefreshCw, WalletCards } from "lucide-react";
import { pssApi } from "@/lib/pss-api";

type Remittance = { id: string; shipment_id?: string | null; amount?: number; status?: string; expected_at?: string | null; settled_at?: string | null; created_at?: string };
export default function CodRemittancePage() {
  const [rows, setRows] = useState<Remittance[]>([]); const [notice, setNotice] = useState("");
  const load = () => void pssApi<{ data: Remittance[] }>("/v1/cod-remittances").then((result) => setRows(result.data ?? [])).catch((error) => setNotice(error instanceof Error ? error.message : "Unable to load COD remittance records."));
  useEffect(() => { load(); }, []);
  return <div className="w-full space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Finance</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">COD remittance</h1><p className="mt-1 text-sm text-muted-foreground">Settlement records from the production API.</p></div><button type="button" onClick={load} className="inline-flex h-9 items-center gap-2 rounded-lg border border-input px-3 text-xs font-semibold"><RefreshCw className="size-3.5" />Refresh</button></header><section className="overflow-hidden rounded-xl border border-border bg-card"><div className="border-b border-border p-4"><div className="flex items-center gap-2"><WalletCards className="size-4 text-primary" /><h2 className="text-sm font-semibold">Remittance ledger</h2></div></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-muted/40 text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{["Reference", "Shipment", "Amount", "Status", "Expected", "Settled"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/70">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3 font-mono font-semibold">{row.id}</td><td className="px-4 py-3">{row.shipment_id ?? "—"}</td><td className="px-4 py-3 font-semibold">₹{Number(row.amount ?? 0).toLocaleString("en-IN")}</td><td className="px-4 py-3">{row.status ?? "pending"}</td><td className="px-4 py-3">{row.expected_at ?? "—"}</td><td className="px-4 py-3">{row.settled_at ?? "Pending"}</td></tr>)}</tbody></table></div> : <div className="grid min-h-[220px] place-items-center p-6 text-center text-sm text-muted-foreground">No production COD remittance records.</div>}</section>{notice && <p role="status" className="text-xs text-muted-foreground">{notice}</p>}</div>;
}
