export type AddressKind = "warehouse" | "consignor" | "consignee";
export type SavedAddressRecord = { id: string; name: string; kind: AddressKind; company: string; address: { line: string; city: string; state: string; pincode: string; country: string }; contact: { name: string; phone: string; email: string }; default: boolean; archived?: boolean; notes?: string };
export type NdrCase = { id: string; shipment: string; client: string; consignee: string; destination: string; courier: string; attempt: number; date: string; reason: string; status: "New" | "Awaiting client action" | "Reattempt requested" | "RTO requested" | "Resolved"; priority: "High" | "Medium"; deadline: string; notes: string };
export type ExceptionCase = { id: string; shipment: string; category: string; severity: "Critical" | "High" | "Medium"; status: "New" | "Acknowledged" | "Awaiting client information" | "Under review" | "Resolved"; date: string; courier: string; location: string; title: string; details: string; action: string };
export const addressKeys: Record<AddressKind, string> = { warehouse: "pss_saved_warehouses", consignor: "pss_saved_pickup_addresses", consignee: "pss_saved_consignee_addresses" };
export const seedAddresses: Record<AddressKind, SavedAddressRecord[]> = {
  warehouse: [{ id: "warehouse-noida", name: "Noida Main Warehouse", kind: "warehouse", company: "PSS Logistics Client", address: { line: "F-452, Sector 63", city: "Noida", state: "Uttar Pradesh", pincode: "201301", country: "India" }, contact: { name: "Warehouse Desk", phone: "+91 98765 43210", email: "warehouse@example.com" }, default: true, notes: "Primary pickup and returns location" }, { id: "warehouse-bengaluru", name: "Bengaluru Fulfilment Hub", kind: "warehouse", company: "PSS Logistics Client", address: { line: "Electronic City Phase 1", city: "Bengaluru", state: "Karnataka", pincode: "560100", country: "India" }, contact: { name: "Dispatch Desk", phone: "+91 98765 43211", email: "dispatch@example.com" }, default: false }],
  consignor: [{ id: "consignor-noida", name: "Noida Main Warehouse", kind: "consignor", company: "PSS Logistics Client", address: { line: "F-452, Sector 63", city: "Noida", state: "Uttar Pradesh", pincode: "201301", country: "India" }, contact: { name: "Warehouse Desk", phone: "+91 98765 43210", email: "warehouse@example.com" }, default: true }],
  consignee: [{ id: "consignee-delhi", name: "Delhi Customer Desk", kind: "consignee", company: "Customer delivery address", address: { line: "Okhla Industrial Area", city: "New Delhi", state: "Delhi", pincode: "110020", country: "India" }, contact: { name: "Receiving Desk", phone: "+91 98765 43212", email: "receiving@example.com" }, default: true }],
};
export const ndrCases: NdrCase[] = [{ id: "NDR-2026-0041", shipment: "312401877", client: "PBS Enterprises", consignee: "GREEN ENERGY EXPERTS", destination: "Pune", courier: "Delhivery", attempt: 1, date: "2026-08-14", reason: "Customer unavailable", status: "Awaiting client action", priority: "High", deadline: "2026-08-17", notes: "Recipient requested a call before the next attempt." }, { id: "NDR-2026-0038", shipment: "313033579", client: "PBS Enterprises", consignee: "Northstar Retail", destination: "Noida", courier: "Delhivery", attempt: 2, date: "2026-08-13", reason: "Address incomplete", status: "New", priority: "High", deadline: "2026-08-18", notes: "Additional landmark is required." }, { id: "NDR-2026-0033", shipment: "312840852", client: "PBS Enterprises", consignee: "Meridian Foods", destination: "Raipur", courier: "Delhivery", attempt: 1, date: "2026-08-12", reason: "Phone unreachable", status: "Reattempt requested", priority: "Medium", deadline: "2026-08-19", notes: "Reattempt has been sent to the courier." }];
export const exceptionCases: ExceptionCase[] = [{ id: "EXC-2026-0091", shipment: "312138483", category: "Weight discrepancy", severity: "High", status: "Awaiting client information", date: "2026-08-15", courier: "Delhivery", location: "Dhanbad", title: "Courier weight differs from booking", details: "Measured weight is higher than the declared weight and requires client review.", action: "Review billing and raise a dispute if needed" }, { id: "EXC-2026-0087", shipment: "313015195", category: "Delivery delay", severity: "Medium", status: "Under review", date: "2026-08-14", courier: "Delhivery", location: "Kolkata", title: "Shipment delayed beyond expected date", details: "The latest scan has not moved the shipment toward the destination branch.", action: "Monitor courier update" }, { id: "EXC-2026-0082", shipment: "312015725", category: "Pickup failed", severity: "High", status: "New", date: "2026-08-13", courier: "Delhivery", location: "Pathanamthitta", title: "Pickup could not be completed", details: "Shipment was not ready when the courier reached the pickup location.", action: "Schedule another pickup" }, { id: "EXC-2026-0079", shipment: "312200621", category: "Documentation", severity: "Critical", status: "Acknowledged", date: "2026-08-12", courier: "Delhivery", location: "Guwahati", title: "Supporting document required", details: "The shipment needs an updated document before the next movement.", action: "Provide document to PSS" }];
export function readAddresses(kind: AddressKind): SavedAddressRecord[] { if (typeof window === "undefined") return seedAddresses[kind]; try { const saved = window.localStorage.getItem(addressKeys[kind]); return saved ? (JSON.parse(saved) as SavedAddressRecord[]).map((item) => ({ ...item, kind, default: Boolean(item.default) })) : seedAddresses[kind]; } catch { return seedAddresses[kind]; } }
export function writeAddresses(kind: AddressKind, records: SavedAddressRecord[]) { window.localStorage.setItem(addressKeys[kind], JSON.stringify(records)); }
