"use client";
import { useEffect, useState } from "react";
import { RefreshCw, Scale } from "lucide-react";
import { pssApi } from "@/lib/pss-api";

type Reconciliation = { id: string; shipment_id?: string; declared_weight_kg?: number; measured_weight_kg?: number; billable_weight_kg?: number; status?: string; created_at?: string; updated_at?: string };
export default function WeightReconciliationPage() {
  const [rows, setRows] = useState<Reconciliation[]>([]); const [notice, setNotice] = useState("");
  const load = () => void pssApi<{ data: Reconciliation[] }>("/v1/weight-reconciliation").then((result) => setRows(result.data ?? [])).catch((error) => setNotice(error instanceof Error ? error.message : "Unable to load weight reconciliation records."));
  useEffect(() => { load(); }, []);
  return <div className="w-full space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Operations</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Weight reconciliation</h1><p className="mt-1 text-sm text-muted-foreground">Declared, measured, and billable weight from production records.</p></div><button type="button" onClick={load} className="inline-flex h-9 items-center gap-2 rounded-lg border border-input px-3 text-xs font-semibold"><RefreshCw className="size-3.5" />Refresh</button></header><section className="overflow-hidden rounded-xl border border-border bg-card"><div className="border-b border-border p-4"><div className="flex items-center gap-2"><Scale className="size-4 text-primary" /><h2 className="text-sm font-semibold">Reconciliation queue</h2></div></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="bg-muted/40 text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{["Record", "Shipment", "Declared kg", "Measured kg", "Billable kg", "Status", "Updated"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/70">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3 font-mono font-semibold">{row.id}</td><td className="px-4 py-3">{row.shipment_id ?? "—"}</td><td className="px-4 py-3">{row.declared_weight_kg ?? "—"}</td><td className="px-4 py-3">{row.measured_weight_kg ?? "Pending"}</td><td className="px-4 py-3 font-semibold">{row.billable_weight_kg ?? "Pending"}</td><td className="px-4 py-3">{row.status ?? "pending"}</td><td className="px-4 py-3">{row.updated_at ?? row.created_at ?? "—"}</td></tr>)}</tbody></table></div> : <div className="grid min-h-[220px] place-items-center p-6 text-center text-sm text-muted-foreground">No production weight reconciliation records.</div>}</section>{notice && <p role="status" className="text-xs text-muted-foreground">{notice}</p>}</div>;
}
